INSERT INTO product_entity (name, price) VALUES ('Notebook Gamer', 4500.00);
INSERT INTO product_entity (name, price) VALUES ('Mouse sem fio', 120.00);
INSERT INTO product_entity (name, price) VALUES ('Teclado mecânico', 300.00);
INSERT INTO product_entity (name, price) VALUES ('Monitor 24"', 800.00);
INSERT INTO product_entity (name, price) VALUES ('Headset', 350.00);
INSERT INTO product_entity (name, price) VALUES ('Webcam HD', 200.00);
INSERT INTO product_entity (name, price) VALUES ('SSD 1TB', 600.00);
INSERT INTO product_entity (name, price) VALUES ('Cadeira Gamer', 1200.00);
INSERT INTO product_entity (name, price) VALUES ('Smartphone Android', 2500.00);
INSERT INTO product_entity (name, price) VALUES ('Tablet 10"', 1500.00);
INSERT INTO product_entity (name, price) VALUES ('Impressora Multifuncional', 700.00);
INSERT INTO product_entity (name, price) VALUES ('HD Externo 2TB', 400.00);
INSERT INTO product_entity (name, price) VALUES ('Placa de Vídeo RTX 4070', 4500.00);
INSERT INTO product_entity (name, price) VALUES ('Fonte 750W', 550.00);
INSERT INTO product_entity (name, price) VALUES ('Gabinete ATX', 350.00);
INSERT INTO product_entity (name, price) VALUES ('Microfone Condensador', 600.00);
INSERT INTO product_entity (name, price) VALUES ('Caixa de Som Bluetooth', 250.00);
INSERT INTO product_entity (name, price) VALUES ('Roteador Wi-Fi 6', 500.00);
INSERT INTO product_entity (name, price) VALUES ('Relógio Smartwatch', 900.00);
INSERT INTO product_entity (name, price) VALUES ('Drone 4K', 3200.00);
